/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_completeadfresult_free: (a: number, b: number) => void;
export const __wbg_get_completeadfresult_optimal_lags: (a: number) => number;
export const __wbg_set_completeadfresult_optimal_lags: (a: number, b: number) => void;
export const __wbg_get_completeadfresult_p_value: (a: number) => number;
export const __wbg_set_completeadfresult_p_value: (a: number, b: number) => void;
export const __wbg_get_completeadfresult_is_stationary: (a: number) => number;
export const __wbg_set_completeadfresult_is_stationary: (a: number, b: number) => void;
export const completeadfresult_critical_values: (a: number) => any;
export const __wbg_adfresult_free: (a: number, b: number) => void;
export const __wbg_get_adfresult_statistic: (a: number) => number;
export const __wbg_set_adfresult_statistic: (a: number, b: number) => void;
export const __wbg_get_adfresult_p_value: (a: number) => number;
export const __wbg_set_adfresult_p_value: (a: number, b: number) => void;
export const __wbg_get_adfresult_is_stationary: (a: number) => number;
export const __wbg_set_adfresult_is_stationary: (a: number, b: number) => void;
export const adfresult_critical_values: (a: number) => any;
export const calculate_complete_adf_test: (a: number, b: number, c: number, d: number) => number;
export const get_adf_p_value_and_stationarity: (a: number) => number;
export const __wbg_set_completeadfresult_test_statistic: (a: number, b: number) => void;
export const __wbg_set_completeadfresult_aic_value: (a: number, b: number) => void;
export const __wbg_get_completeadfresult_test_statistic: (a: number) => number;
export const __wbg_get_completeadfresult_aic_value: (a: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_start: () => void;
